services:
  backend:
    build: ./Backend
    container_name: fraud-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/frauddb.sqlite:/app/frauddb.sqlite
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build: ./Frontend
    container_name: fraud-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
